name: Update Gallery Index
on:
  push:
    paths:
      - 'img/**' # Si attiva solo quando aggiungi foto nella cartella img

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate JSON index
        run: |
          echo "[" > gallery.json
          ls img | grep -E "\.(jpg|jpeg|png|webp)$" | sed 's/.*/"&",/' | sed '$ s/,$//' >> gallery.json
          echo "]" >> gallery.json

      - name: Commit and push changes
        run: |
          git config --global user.name "Gallery Bot"
          git config --global user.email "bot@github.com"
          git add gallery.json
          git commit -m "Aggiornamento automatico galleria" || exit 0
          git push
